project:
  type: website

website:
  title: "Data project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - Data.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: source

