project:
  type: website

website:
  title: "Data Project"
  navbar:
    position: sticky
    left:
      - href: index.qmd
        text: Home
      - project.qmd
      - about.qmd
      - Data.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: source

