---
title: "Project"
execute: 
  warning: false
---
```{r}
#| label: setup
#| message: false
#| warning: false
#| output: false
#| echo: false
library(tidyverse)
library(ggplot2)
library(gganimate)
library(gifski)
library(ggthemr)
library(scales)
library(patchwork)
```
In this project, the selected players are all the point guards with averages of 25 or more points per game.

```{r}
#| message: false
#| echo: false
points  <- tribble(
  ~Player, ~PointsPerGame,
  "Steph Curry",   26.4,
  "Kyrie Irving",   25.6,
  "De'Aaron Fox",   26.6,
  "Luka Doncic", 33.9,
  "Trae Young", 25.7,
  "Jalen Brunson", 28.7,
  "Ja Morant", 25.1,
  "Tyrese Maxey", 25.9
)
rebounds  <- tribble(
  ~Player, ~ReboundsPerGame,
  "Steph Curry",   4.5,
  "Kyrie Irving",   5.0,
  "De'Aaron Fox",   4.6,
  "Luka Doncic", 9.2,
  "Trae Young", 2.8,
  "Jalen Brunson", 3.6,
  "Ja Morant", 5.6,
  "Tyrese Maxey", 3.7
)

assists  <- tribble(
  ~Player, ~AssistsPerGame,
  "Steph Curry",   5.1,
  "Kyrie Irving",   5.2,
  "De'Aaron Fox",   4.6,
  "Luka Doncic", 9.8,
  "Trae Young", 10.8,
  "Jalen Brunson", 6.7,
  "Ja Morant", 8.1,
  "Tyrese Maxey", 6.2
)
steals  <- tribble(
  ~Player, ~StealsPerGame,
  "Steph Curry",   0.7,
  "Kyrie Irving",   1.3,
  "De'Aaron Fox",   2.0,
  "Luka Doncic", 1.4,
  "Trae Young", 1.3,
  "Jalen Brunson", 0.9,
  "Ja Morant", 0.8,
  "Tyrese Maxey", 1.0
)

blocks  <- tribble(
  ~Player, ~BlocksPerGame,
  "Steph Curry",   0.4,
  "Kyrie Irving",   0.5,
  "De'Aaron Fox",   0.4,
  "Luka Doncic", 0.5,
  "Trae Young", 0.2,
  "Jalen Brunson", 0.2,
  "Ja Morant", 0.6,
  "Tyrese Maxey", 0.5
)
TOs  <- tribble(
  ~Player, ~TOsPerGame,
  "Steph Curry",   2.8,
  "Kyrie Irving",   1.8,
  "De'Aaron Fox",   2.6,
  "Luka Doncic", 4,
  "Trae Young", 4.4,
  "Jalen Brunson", 2.4,
  "Ja Morant", 3,
  "Tyrese Maxey", 1.7
)
fgs  <- tribble(
  ~Player, ~fgpercent,
  "Steph Curry",   45.0,
  "Kyrie Irving",   49.7,
  "De'Aaron Fox",   46.5,
  "Luka Doncic", 48.7,
  "Trae Young", 43.0,
  "Jalen Brunson", 47.9,
  "Ja Morant", 47.1,
  "Tyrese Maxey", 45
)
winpercentdiff  <- tribble(
  ~Player, ~WinPercentageDiff,
  "Steph Curry",   0.206,
  "Kyrie Irving",   0.214,
  "De'Aaron Fox",   0.068,
  "Luka Doncic", 0.323,
  "Trae Young", -0.093,
  "Jalen Brunson", 0.436,
  "Ja Morant", 0.379,
  "Tyrese Maxey", 0.282
)
```

```{r}
#| echo: false
ggthemr("flat")
# Create individual plots
points_plot <- ggplot(points, aes(y = Player, x = PointsPerGame, fill = Player)) +
  geom_col() +
  labs(
    title = "Points Per Game of Selected Players",
    y = "Player",
    x = "Points Per Game",
    subtitle = "A point is how a player scores. It is worth 2 points if the shot is inside the 3 point line,\nand it is worth 3 points if it is outside the 3 point line",
    caption = "Luka Doncic has the most points per game,\nfollowed by Jalen Brunson"
  ) +
  theme(
    plot.caption = element_text(size = 12) 
  )

rebounds_plot <- rebounds |> select(Player, ReboundsPerGame) |> ggplot(aes(y = Player, x = ReboundsPerGame))+
  geom_col(aes(fill = Player))+
  labs(title = "Rebounds Per Game of Selected Players",subtitle = "A rebound is when the player catches the ball after someone shoots and misses.", y = "Player", x = "Rebounds Per Game", caption = "Luka Doncic has the most rebounds per game by far, \n followed by Ja Morant")+ theme(
  plot.caption = element_text(size = 12)  
)

assists_plot <- assists |> select(Player, AssistsPerGame) |> ggplot(aes(y = Player, x = AssistsPerGame))+
  geom_col(aes(fill = Player))+
  labs(title = "Assists Per Game of Selected Players", subtitle = "An assist is when a player passes the ball to another player who then scores points.", y = "Player", x = "Assists Per Game", caption = "Trae Young has the most assists per game, \n followed by Luka Doncic")+ 
  theme(
  plot.caption = element_text(size = 12)  
)

steals_plot <- steals |> select(Player, StealsPerGame) |> ggplot(aes(y = Player, x = StealsPerGame))+
  geom_col(aes(fill = Player))+
  labs(title = "Steals Per Game of Selected Players", subtitle = "A steal is when a player takes the ball from another player, \n leading to the other team gaining possesion.", y = "Player", x = "Steals Per Game", caption = "De'Aaron Fox has the most steals per game by far, \n followed by Luka Doncic")+ 
  theme(
  plot.caption = element_text(size = 12)  
)

blocks_plot <- blocks |> select(Player, BlocksPerGame) |> ggplot(aes(y = Player, x = BlocksPerGame))+
  geom_col(aes(fill = Player))+
  labs(title = "Blocks Per Game of Selected Players", subtitle = "A block is when a player deflects a shot that the opposing team tries to shoot.",y = "Player", x = "Blocks Per Game", caption = "Ja Morant has the most blocks per game, \n followed by Luka Doncic and Kyrie Irving")+ theme(
  plot.caption = element_text(size = 12)  
)

TOs_plot <- TOs |> select(Player, TOsPerGame) |> ggplot(aes(y = Player, x = TOsPerGame))+
  geom_col(aes(fill = Player))+
  labs(title = "Turnovers Per Game of Selected Players", subtitle = "A turnover is when a player gives up the ball to the opposing team. Fewer turnovers is better.", y = "Player", x = "Turnovers Per Game", caption = "Tyrese Maxey has the least turnovers per game,\n followed by Kyrie Irving")+ 
  theme(
  plot.caption = element_text(size = 12)  
)

fgs_plot <- fgs |> select(Player, fgpercent) |> ggplot(aes(y = Player, x = fgpercent))+
  geom_col(aes(fill = Player))+
  labs(title = "Field Goal Percentage of Selected Players", subtitle = "Field Goal percentage is the percentage of shots that they shoot that go in.", y = "Player", x = "Field goals percentage", caption = "Luka Doncic and Kyrie Irving have the highest field goal percentage")+ 
  theme(
  plot.caption = element_text(size = 12)  
)

winpercentdiff_plot <- winpercentdiff |> select(Player, WinPercentageDiff) |> ggplot(aes(y = Player, x = WinPercentageDiff))+
  geom_col(aes(fill = Player))+
  labs(title = "Win Percentage Difference of Selected Players", subtitle = "Win Percentage Difference is the difference in the percentage of games that they win \n with a player available vs unavailable. Note that this is in decimals, not percentage.", y = "Player", x = "Winning Percentage Difference", caption = "Jalen Brunson had the highest winning percentage difference, \n followed by Ja Morant")+ 
  theme(
  plot.caption = element_text(size = 12)  
)


print(points_plot)
print(rebounds_plot)
print(assists_plot)
print(steals_plot)
print(blocks_plot)
print(TOs_plot)
print(fgs_plot)
print(winpercentdiff_plot)

```



In conclusion, Luka Doncic is the best point guard in NBA this season, followed by Kyrie Irving, Ja Morant, and Jalen Brunson(not in any specific order). I figured this out by looking at the graphs, and these players were consistently at the top.